[application]

# dioxus project name
name = "movie-palace"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Movie Palace | Rate your favorite content and save for later"

[web.watcher]

index_on_404 = true

watch_path = ["src", "unocss.config.ts"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["uno.css", "tailwind.min.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []
